### ISSUE TITLE
Invert non-essential deps in github.com/pilosa/pilosa

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1093]
### Description
Pilosa's top level package has a number of direct dependencies which can be problematic. We should hide these dependencies behind interfaces so that pilosa doesn't need to import them directly. Then we can wire up the implementations in `github.com/pilosa/pilosa/server`. This is in keeping with @benbjohnson's widely circulated packaging philosophy https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1 and has a number of benefits.

For a concrete example: at the moment, I'm trying to use `github.com/pilosa/pilosa/test` (from the PDK) which imports pilosa in order to get `pilosa.URI`. Pilosa directly imports `github.com/shirou/gopsutil` which is causing a build issue which I'm not quite clear on, but isn't relevant to this ticket. The `gopsutil` package is only needed by Pilosa's diagnostics package which isn't critical to normal Pilosa operations. If the diagnostics functionality where hidden behind an interface, it could easily be stubbed/mocked or replaced as necessary by various users of Pilosa.

I'm intending this as an umbrella ticket and will break the following out into separate issues:
- [x] diagnostics (pulls in a couple things) #1094 
- [x] monitorRuntime (pulls in gcnotifier) #1095 
- [x] attr store (pulls in boltdb) (depending on perf hit) #1096 
- [x] web console (pulls in statik) #1097 
- [x] LRU cache github.com/golang/groupcache/lru (this one could possibly just be copied in rather than vendoring the dep) #1098 
- [x] Move handler.go to subpackage to invert net/http dependency #1153

### Success criteria (What criteria will consider this ticket closeable?)

Once all the above boxes are checked!

**Comment by yuce** [comment]
We can decouple web console, and probably diagnostics too if we had HTTP handler plugins: https://github.com/pilosa/pilosa/tree/handler-plugins
